name: Derek Kedziora
description: A lighthearted look at linguistics, teaching and learning English and the philosophy surrounding it.
github: derekkedziora
markdown: kramdown
url: derek.com.ua
permalink: blog/:title
gems:
  - jekyll-sitemap
