name: the flow of language
author: Derek Kedziora
description: The musings of a linguist about editing, writing, teaching English and related tangents.
github: derekkedziora
markdown: kramdown
url: derek.com.ua
permalink: blog/:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
collections:
  lesson-archives:
    output: true
    permalink: /lesson-archives/:title
  lessons:
    output: true
    lessons: lessons/:title
