name: the flow of language
author: Derek Kedziora
description: A lighthearted look at linguistics, teaching, learning English and life.
github: derekkedziora
markdown: kramdown
url: derek.com.ua
permalink: blog/:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
